container:
  image: debian:bullseye-slim  # Use debian 11 for lcov 1.14
  cpu: 2
  memory: 6G
timeout_in: 90m
env:
  MAKEJOBS: "-j3"
  DOCKER_PACKAGES: "python3-zmq libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libdb5.3++-dev libsqlite3-dev libminiupnpc-dev libzmq3-dev lcov build-essential libtool autotools-dev automake pkg-config bsdmainutils bsdextrautils clang llvm"
  LC_ALL: "C.UTF-8"
  ID_SSH: "ENCRYPTED[9d3aa76775f8b2c0018725ae77ecb6d8951fbb74e29bd5172aad53393fbe5ba962944ba2dba65b13c514e21139e74548]"
global_task_template: &GLOBAL_TASK_TEMPLATE
  install_packages_script:
    - apt update && apt install -y git
  prepare_script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - echo "$ID_SSH" > ~/.ssh/id_ssh
    - chmod 600 ~/.ssh/id_ssh
    - git config user.name "CI/${CIRRUS_REPO_FULL_NAME}"
    - git config user.email "ci@none.org"
    - git remote add origin_git git@github.com:${CIRRUS_REPO_FULL_NAME}.git  # Add remote so we can push there
    - git fetch origin_git
  install_2_script:
    - apt-get install --no-install-recommends --no-upgrade -qq $DOCKER_PACKAGES
    - git clone git@github.com:bitcoin/bitcoin.git
    - cd bitcoin
    - export MASTER_COMMIT=$(git log --format='%H' -1)
  before_script:
    - sed -i 's|functional/test_runner.py |functional/test_runner.py --timeout-factor=10 |g' ./Makefile.am
    - ./autogen.sh
    - mkdir build && cd build


task:
  name: "lcov"
  << : *GLOBAL_TASK_TEMPLATE
  use_compute_credits: true
  script:
    - ../configure --enable-zmq --with-incompatible-bdb --enable-lcov --enable-lcov-branch-coverage --disable-bench --enable-extended-functional-tests
    - make $MAKEJOBS
    - make cov
    - cd ../../
    - git checkout master
    - export OTHER_COV_COMMIT=$(git log -1 --grep="fuzz_cov results" --format=%H)
    - git reset --hard origin_git/master_init
    - git cherry-pick $OTHER_COV_COMMIT --allow-empty
    - sudo chown -R $(id -u):$(id -g) ./bitcoin/build/
    - cp -r ./bitcoin/build/*coverage ./
    - git add ./*coverage* && git commit -m "lcov results for upstream@${MASTER_COMMIT}"
    - git push origin_git master -f


task:
  name: "fuzz_cov"
  << : *GLOBAL_TASK_TEMPLATE
  script:
        - git clone https://github.com/bitcoin-core/qa-assets
        - ../configure --enable-fuzz --with-sanitizers=fuzzer --enable-lcov --enable-lcov-branch-coverage CC=clang CXX=clang++
        - make $MAKEJOBS
        - make cov_fuzz
        - cd ../../
        - git checkout master
        - export OTHER_COV_COMMIT=$(git log -1 --grep="lcov results" --format=%H)
        - git reset --hard origin_git/master_init
        - git cherry-pick $OTHER_COV_COMMIT --allow-empty
        - sudo chown -R $(id -u):$(id -g) ./bitcoin/build/
        - cp -r ./bitcoin/build/*coverage ./
        - git add ./*coverage* && git commit -m "fuzz_cov results for upstream@${MASTER_COMMIT}"
        - git push origin_git master -f
